---
title: "Milk Prices Case Study"
author: "Bao Doquang, Dhwanit Agarwal, Akksay Singh and Shristi Singh"
date: "February 14th, 2019"
output: md_document
---

#Milk Prices Case Study#
The data in milk.csv contains a random sample of daily sales figures for a small neighborhood grocery store of cartons of milk.The "price" column gives the price at which the milk was sold that day and the "sales" column says how many units were sold that day. The store's wholesale cost of milk is c dollars per carton. As the merchants, we want to maximize profit. Assuming that P is "price charged", Q is "quanity sold", N is "net or gross profit" and "c" is whole sale cost. Gross Profit will be the profit we will make on each item sold times the number of items sold. Hence our equation is N=(P-c)*Q. We need to maximize this equation but we can not use calculus to maximize it becasue we if we try to take the derivative dN/dp and set it equal to 0 then we run into the problem of price and quantitiy being coupled in this equation. So as we increase the price people demand less. Thus our equation is (P-C) times f(p) since Q=f(p). We have to estimate f(p) which is the demand curve. The estimate of the demand curve is in a power law format so we have Q = alpha times Price raised to the power beta. Here beta is the price elasticity of demand. To fit the power law equation we take the log of both sides of our equation and we have log(Q) = log(alpha) + beta (log(P)). This is a linear function, in log(Q) versus log(P) so we can use the lm fuction to estimate the value of alpha and beta. As you can see from the R out that alpha = 4.721 and beta = -1.619. Hence our equation is Q = e^4.721-p^(-1.619). This gives total gross profit of N = (P-C) (e^4.7(P^(-1.62)).As per question, c = 1. So our equation becomes N = Q(p)(P-C)=(e^4.721-p^(-1.619))(P-1). Lastly, now that we have our gross profit function, we can use calculus or as simply told in class, plot and point to the maximum. The plot is shown, and the ideal price found is 2.61 dollars. 

```{r} 
library(mosaic)
library(tidyverse)

milk <- read.csv("milk.csv")

plot(sales~price, milk)
plot(log(sales)~log(price), milk)
ped <- lm(log(sales) ~ log(price), milk)
ped
# log(Q)=4.7-1.62log(p)
##Q = (e^4.7)p^-1.62

curve((x-1)*110*x^(-1.62), from=2, to=5)
curve((x-1)*110*x^(-1.62), from=2.5, to=2.7)

```
